### ISSUE TITLE
Docker Registry UI

### ISSUE THREAD

**Issue by wildloop** [cloudfoundry-community/docker-registry-boshrelease#37]
What about adding embedded Docker Registry UI?
There are some ready static apps that consumes docker registry v2 rest endpoints, e.g.: https://github.com/Joxit/docker-registry-ui

I can do PR.

**Comment by jhunt** [comment]
Sounds good!

**Comment by wildloop** [comment]
I've made PR https://github.com/Joxit/docker-registry-ui/pull/50 to adapt the app to our needs.
While waiting for the reaction, I released the new version of [`docker-registry-ui`](https://github.com/wildloop/docker-registry-ui/releases/tag/0.4.1) that includes these changes.

In the fork of [`docker-registry-boshrelease`](https://github.com/wildloop/docker-registry-boshrelease/commit/788d520762835c18608a4014a1b0829d36a72b25) I've:
- added the new package `docker-registry-ui` with script that downloads the released app
- modified nginx job - now it serves this app too

I do not know if this is the right way to implement this issue in the BOSH.
It seems to me that the use of blob would be better, but I do not know how to download it from the external repository.

I am asking for advice :)

**Comment by jhunt** [comment]
Rather than download from GitHub during the compilation step, you can download it yourself, and then `bosh add-blob` to get the blob into your local blobstore.  Since it is a released asset on GitHub, I can pull that down and upload it to the S3 blobstore to make it official, when I merge the PR.  We do this regularly, just ask @mattsurabian and @kitsirota.

Later, when upstream merges your PR and cuts their own release, we can switch to that asset for the blob; we would use the same process (an issue or a PR to get the new asset integrated, and a manual upload to the blobstore by myself or another community member with access)

**Comment by jhunt** [comment]
@wildloop is this still something you are interested in pursuing?
